/** @type {import('next').NextConfig} */
const nextConfig = {
    images: {
      domains: [
        'upload.wikimedia.org', 
        'pbs.twimg.com', 
        'i.pinimg.com', 
        'www.jagranimages.com', 
        'www.jansatta.com', 
        'staticimg.amarujala.com',
        "unsplash.com",
        "images.unsplash.com",
        "scontent.fisb29-1.fna.fbcdn.net",
        "the.ismaili",
        "lh3.googleusercontent.com",
        "www.apricottours.pk",
        "https://encrypted-tbn0.gstatic.com",
        "marketplace.canva.com",
        "dynamic-media-cdn.tripadvisor.com",
        "www.exploria.pk",
        "hunzaguidespakistan.com",
        "mytrip.pk",
        "pakistantourntravel.com",
        "i.ytimg.com",
        "www.natureadventureclub.pk",
        "media.istockphoto.com",
        "www.pakvoyager.com",
        "assets.bucketlistly.blog",
        "thesilenttraveler.com",
        "png.pngtree.com",
        "www.imusafir.pk",
        "rozefstourism.com",
        "besttourpoints.com",
        "eagleeye.com.pk",
        "prestinetravels.com",
        "cdn.tourradar.com",
        "pakistanadventurous.com",
        "trangoadventure.com",
        "res.cloudinary.com",
        "media-cdn.tripadvisor.com",
        "i.ytimg.com",
        "www.wildfrontierstravel.com",
        "i.natgeofe.com",
        "upload.wikimedia.org",
        "cdn.bookatrekking.com",
        "www.travelgirls.pk",
        "traveloguers.com",
        "induscaravan.com",
        "expatstraveltogether.com",
        "www.reddit.com",
        "pyaraskardu.com"
      ],
    },
  };
  
  export default nextConfig;
  